dataset:
  name: mp3d
  num_views_low_res: 8
  num_views_high_res: 6
  image_root_dir: training/mp3d_skybox
  fov: 90
  rot_low_res: 45
  rot_high_res: 45
  resolution: 256
  resolution_high_res: 1024
  crop_size_high_res: 384

train:
  log_dir: sd_upsampler
  lr: 0.0001

test:
  fuse_type: single # multidiff

model:
  guidance_scale: 9.
  diff_timestep: 1
  low_res_noise_level: 20 # from the default SD upsampler setting
  model_type: upsample
  upsample_model:
    model_id: stabilityai/stable-diffusion-x4-upscaler
    num_coarse_cp_blocks: 5
    lora_layers: False
    homo_cp_attn: True
    diff_timestep: 75
    multiframe_fuse: True
  base_model:
    diff_timestep: 50
    model_id: stabilityai/stable-diffusion-2-base
    lora_layers: True
    
